### PR TITLE
H2M-Mod Support

### PR DESCRIPTION
**Pull request by Lierrmm**
Add support for H2M-Mod Client.

### CODE REVIEW

**Review by RaidMax — APPROVED** [review]

**Comment by RaidMax** [comment]
Would it be possible to get these commits signed before merging? It’s a recent protection I applied to the repo. If you’re not familiar with the process I can override.

**Comment by Lierrmm** [comment]
Should be signed now 👍

**Comment by realviolent** [comment]
https://x.com/H2Multiplayer/status/1824167247436542167 H2-Mod shutdown

**Comment by RaidMax** [comment]
> https://x.com/H2Multiplayer/status/1824167247436542167 H2-Mod shutdown

Uh… obviously this has been known for a while. Also this PR was merged before the “shutdown” so I’m not really certain what your purpose of commenting was..

**Pull request merged**
